import type { Metadata } from "next";
import "./globals.css";
import SignOutButton from "./components/SignOutButton";
import { ErrorProvider } from '@/context/ErrorContext';
import { Toaster } from "@/components/ui/toaster";
import { GlobalProvider } from "@/context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ErrorProvider>
          <GlobalProvider>
            <div className="max-w-[800px] w-full m-auto">
              {/* <SignOutButton /> */}
              {children}
              <Toaster />
            </div>
          </GlobalProvider>
        </ErrorProvider>
      </body>
    </html>
  );
}
